### ISSUE TITLE
Getting an error with `FeatureName` 

### ISSUE THREAD

**Issue by kalapi** [googlefonts/fez#12]
I have this the following Fez code:

```
Feature ss04 {
	FeatureName "[Tamil] Looped uuMatra style";
	Substitute aa-tamil -> aa-tamil.ss04 <<tml2/dflt>>;
};
```

And i'm getting the following traceback:

```
Traceback (most recent call last):
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/fez/__init__.py", line 412, in parseString
    rv = self.transformer.transform(self.parser.parse(s))
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 161, in transform
    return self._transform_tree(tree)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 156, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 146, in _transform_children
    res = self._transform_tree(c)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 156, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 146, in _transform_children
    res = self._transform_tree(c)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 156, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 146, in _transform_children
    res = self._transform_tree(c)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 157, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 128, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "statement":

FeatureName() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/bin/fez2fea", line 42, in <module>
    p.parseFile(args.fee)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/fez/__init__.py", line 403, in parseFile
    return self.parseString(data)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/fez/__init__.py", line 416, in parseString
    raise e.orig_exc
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/lark/visitors.py", line 124, in _call_userfunc
    return f(children)
  File "/Users/UT-development/Documents/_Programming/testing_environments/FEZzing/lib/python3.8/site-packages/fez/__init__.py", line 492, in statement
    transformer = requested_plugin.transformer(self.parser)
TypeError: FeatureName() takes no arguments
```

**Comment by ctrlcctrlv** [comment]
https://github.com/googlefonts/fez/blob/a73d5e622d9a87e2037a462332743c121e328cbd/lib/fez/Feature.py#L88

**Comment by ctrlcctrlv** [comment]
Yeah this needs a patch to fontFeatures to fix.

**Comment by ctrlcctrlv** [comment]
> The following name IDs are pre-defined, and they apply to all platforms unless indicated otherwise. Name IDs 26 to 255, inclusive, are reserved for future standard names. Name IDs 256 to 32767, inclusive, are reserved for font-specific names such as those referenced by a font’s layout features.

I think this means that I can reference a name ID from 256 to 32767 when writing the feature then output the right name table entry...

**Comment by ctrlcctrlv** [comment]
yeah

> 
> <p>The featureParamsOffset field of the Feature Table of these GSUB 
> features may be set to 0, or to an offset to a Feature Parameters table.
>  The Feature Parameters table for this feature is structured as follows:</p>
> <div class="has-inner-focus">
> 
> Type | Name | Description
> -- | -- | --
> uint16 | format | Format number is set to 0.
> uint16 | featUiLabelNameId | The 'name' table name ID that specifies a string (or strings, for  multiple languages) for a user-interface label for this feature. (May be  NULL.)
> uint16 | featUiTooltipTextNameId | The 'name' table name ID that specifies a string (or strings, for  multiple languages) that an application can use for tooltip text for  this feature. (May be NULL.)
> uint16 | sampleTextNameId | The 'name' table name ID that specifies sample text that illustrates the effect of this feature. (May be NULL.)
> uint16 | numNamedParameters | Number of named parameters. (May be zero.)
> uint16 | firstParamUiLabelNameId | The first 'name' table name ID used to specify strings for  user-interface labels for the feature parameters. (Must be zero if  numParameters is zero.)
> uint16 | charCount | The count of characters for which this feature provides glyph variants. (May be zero.)
> uint24 | character[charCount] | The Unicode Scalar Value of the characters for which this feature provides glyph variants.
> 
> </div>

**Comment by kalapi** [comment]
> https://github.com/googlefonts/fez/blob/a73d5e622d9a87e2037a462332743c121e328cbd/lib/fez/Feature.py#L88

Should've checked the source code 🙃

**Comment by ctrlcctrlv** [comment]
I sort of have a patch for this:

# fez
```diff
diff --git a/lib/fez/Feature.py b/lib/fez/Feature.py
index d56eff6..901da50 100644
--- a/lib/fez/Feature.py
+++ b/lib/fez/Feature.py
@@ -68,7 +68,7 @@ class Feature(FEZVerb):
         oddStatements = []
         def wrap_and_flush():
             nonlocal oddStatements
-            
+
             if len(oddStatements) > 0:
                 self.parser.fontfeatures.addFeature(featurename, [Routine(rules=[r for r in oddStatements if isinstance(r, Rule)])])
             oddStatements = []
@@ -88,4 +88,5 @@ class Feature(FEZVerb):
 # FIXME: Implement this.
 class FeatureName:
     def action(self, args):
-      pass
+        (name,) = args
+        self.parser.fontfeatures.nice_names[self.parser.current_feature] = name
```

# fontFeatures
```diff
diff --git a/fontFeatures/__init__.py b/fontFeatures/__init__.py
index 4c16d66..9b13359 100644
--- a/fontFeatures/__init__.py
+++ b/fontFeatures/__init__.py
@@ -52,6 +52,7 @@ class FontFeatures:
         self.namedClasses = {}  #: A mapping of named classes to a list of glyph names which make up the class.
         self.routines = []  #: All of the layout routines used in this font.
         self.features = OrderedDict()  #: An ordered dictionary mapping feature tags to a list of routine references.
+        self.nice_names = {}
         self.anchors = {}  #: A dictionary mapping glyph names to a dictionary of anchor names / positions.
         self.symbols = {}
         self.glyphclasses = {}  #: A dictionary mapping glyph names to their categories.
@@ -128,7 +129,7 @@ class FontFeatures:
         self.namedClasses[name] = glyphs
         return name
 
-    def addFeature(self, name, rs):
+    def addFeature(self, name, rs, user_facing_name=None):
         """Add Routines to a named feature.
 
         Args:
@@ -142,6 +143,8 @@ class FontFeatures:
             if isinstance(r, Routine):
                 r = self.referenceRoutine(r)
             self.features[name].append(r)
+        if user_facing_name:
+            self.nice_names[name] = user_facing_name
 
 
     def allRules(self, ruletype=None):
diff --git a/fontFeatures/ttLib/FontFeatures.py b/fontFeatures/ttLib/FontFeatures.py
index e2b569a..ce1a417 100644
--- a/fontFeatures/ttLib/FontFeatures.py
+++ b/fontFeatures/ttLib/FontFeatures.py
@@ -17,6 +17,7 @@ from fontTools.ttLib import newTable
 from collections import OrderedDict
 import itertools
 from fontTools.varLib.varStore import OnlineVarStoreBuilder
+from fontTools import feaLib
 
 
 def buildBinaryFeatures(self, font, axes=[]):
@@ -179,6 +180,41 @@ def separate_by_stage(the_big_map, stage):
             stage_map[k] = v
     return stage_map
 
+def buildFeatureParams(self, tag):
+    self.cv_parameters_ = self.nice_names
+    params = None
+    if tag == "size":
+        params = otTables.FeatureParamsSize()
+        (
+            params.DesignSize,
+            params.SubfamilyID,
+            params.RangeStart,
+            params.RangeEnd,
+        ) = self.size_parameters_
+        if tag in self.featureNames_ids_:
+            params.SubfamilyNameID = self.featureNames_ids_[tag]
+        else:
+            params.SubfamilyNameID = 0
+    elif tag in self.cv_parameters_:
+        params = otTables.FeatureParamsCharacterVariants()
+        params.Format = 0
+        params.FeatUILabelNameID = self.cv_parameters_ids_.get(
+            (tag, "FeatUILabelNameID"), 0
+        )
+        params.FeatUITooltipTextNameID = self.cv_parameters_ids_.get(
+            (tag, "FeatUITooltipTextNameID"), 0
+        )
+        params.SampleTextNameID = self.cv_parameters_ids_.get(
+            (tag, "SampleTextNameID"), 0
+        )
+        params.NumNamedParameters = self.cv_num_named_params_.get(tag, 0)
+        params.FirstParamUILabelNameID = self.cv_parameters_ids_.get(
+            (tag, "ParamUILabelNameID_0"), 0
+        )
+        params.CharCount = len(self.cv_characters_[tag])
+        params.Character = self.cv_characters_[tag]
+    return params
+
 def makeTable(self, tag, font):
     """Compiles a binary GSUB/GPOS table."""
     table = getattr(otTables, tag, None)()
@@ -228,7 +264,7 @@ def makeTable(self, tag, font):
             frec = otTables.FeatureRecord()
             frec.FeatureTag = feature_tag
             frec.Feature = otTables.Feature()
-            # frec.Feature.FeatureParams = self.buildFeatureParams(feature_tag)
+            frec.Feature.FeatureParams = buildFeatureParams(self, feature_tag)
             frec.Feature.LookupListIndex = list(lookup_indices)
             frec.Feature.LookupCount = len(lookup_indices)
             table.FeatureList.FeatureRecord.append(frec)
```

**Comment by simoncozens** [comment]
I'm not convinced by that. We have to cover both [cv01](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#8.d) and [ss01](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#8.c), and we also have to emit them in the FEA outputter too. I'll think about it.

**Comment by ctrlcctrlv** [comment]
Thanks Simon, that's why I didn't PR it, just dumped the diff output here so it wouldn't be lost. :-)

**Comment by ctrlcctrlv** [comment]
I also had the idea of just removing the `FeatureName` command and adding it as a BEFOREBRACE grammar item. Thoughts on that?
